name: bildirim_kullanimi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.3.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
